### ISSUE TITLE
Any way to provide custom plugins for track mappings that leverage them

### ISSUE THREAD

**Issue by bbguitar77** [elastic/rally-tracks#10]
Just didn't see any documentation around this, maybe I missed it though

**Comment by danielmitterdorfer** [comment]
I guess this is more of a question than an issue, so I'm closing it. Please feel free to reopen if I misunderstood you. :)

At the moment, none of the standard tracks uses custom plugins on master but percolator uses it on the 1.7 and 2 branch. See e.g. https://github.com/elastic/rally-tracks/blob/2/percolator/track.py

The Rally documentation also covers [custom parameter sources](http://esrally.readthedocs.io/en/stable/adding_tracks.html#custom-parameter-sources) and [custom runners](http://esrally.readthedocs.io/en/stable/adding_tracks.html#custom-runners).

Hint: We have forum for Rally related questions on Discuss: https://discuss.elastic.co/c/elasticsearch/rally
