### ISSUE TITLE
200s-in-range query latency is unstable

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally-tracks#149]
In the [nightly benchmarks](https://elasticsearch-benchmarks.elastic.co/#tracks/http-logs/nightly/default/30d) we've observed that latency is unstable for the query `200s-in-range`:

![nightly-basic-http_logs-4g-200s-in-range-latency](https://user-images.githubusercontent.com/1699576/101605901-08177500-3a03-11eb-87e0-adca364ae3d7.png)

When we inspect latency over time in a single benchmark, we see that it is consistenly rising:

![latency-200s-in-range](https://user-images.githubusercontent.com/1699576/101606176-5cbaf000-3a03-11eb-8bb9-1520806e116b.png)

Service time in a single benchmark is around 26ms:

![nightly-basic-http_logs-4g-200s-in-range-service-time](https://user-images.githubusercontent.com/1699576/101606303-8542ea00-3a03-11eb-8380-0a386cac9f60.png)

This suggests that the target throughput is too high for that configuration and we proposing dropping it, so one request is issued every 30ms, meaning target througput should be lowered to 1 / 30ms = 33 ops/s.

**Comment by nik9000** [comment]
I've know about this for a bit. I have an in flight or that switches the
runtime fields to load from _source which will change them. I was also
waiting on proper kibana access to read the throughput numbers. I got that
yesterday.

I do think it is worth getting my other change merged before working too
hard on aligning the targets. But I'll have a look today to see if there is
something I can do in the mean time.

**Comment by nik9000** [comment]
Ah! This isn't the runtime run. Yeah, I can certainly lower it.
