### ISSUE TITLE
Some indicators are empty

### ISSUE THREAD

**Issue by hexian55** [elastic/rally-tracks#15]
hi
my esrally output:
------------------------------------------------------
    _______             __   _____
   / ____(_)___  ____ _/ /  / ___/_________  ________
  / /_  / / __ \/ __ `/ /   \__ \/ ___/ __ \/ ___/ _ \
/ __/ / / / / / /_/ / /   ___/ / /__/ /_/ / /  /  __/
/_/   /_/_/ /_/\__,_/_/   /____/\___/\____/_/   \___/
------------------------------------------------------

|   Lap |                          Metric |            Operation |     Value |   Unit |
|------:|--------------------------------:|---------------------:|----------:|-------:|
|   All |                   Indexing time |                      |   33.2486 |    min |
|   All |                      Merge time |                      |   7.03988 |    min |
|   All |                    Refresh time |                      |   1.28523 |    min |
|   All |                      Flush time |                      | 0.0920167 |    min |
|   All |             Merge throttle time |                      |  0.526933 |    min |
|   All |                Median CPU usage |                      |   468.176 |      % |
|   All |              Total Young Gen GC |                      |    15.326 |      s |
|   All |                Total Old Gen GC |                      |     1.184 |      s |
|   All |        Heap used for doc values |                      | 0.0941429 |     MB |
|   All |             Heap used for terms |                      |   13.1741 |     MB |
|   All |             Heap used for norms |                      | 0.0684814 |     MB |
|   All |            Heap used for points |                      |  0.579043 |     MB |
|   All |     Heap used for stored fields |                      |  0.624725 |     MB |
|   All |                   Segment count |                      |        89 |        |
|   All |                  Min Throughput |         index-append |           |        |
|   All |               Median Throughput |         index-append |           |        |
|   All |                  Max Throughput |         index-append |           |        |
|   All |                  Min Throughput |          force-merge |           |        |
|   All |               Median Throughput |          force-merge |           |        |
|   All |                  Max Throughput |          force-merge |           |        |
|   All |                  Min Throughput |          index-stats |           |        |
|   All |               Median Throughput |          index-stats |           |        |
|   All |                  Max Throughput |          index-stats |           |        |
|   All |       50.0th percentile latency |          index-stats |    1.5946 |     ms |
|   All |       90.0th percentile latency |          index-stats |   1.67269 |     ms |
|   All |       99.0th percentile latency |          index-stats |    2.5369 |     ms |
|   All |      100.0th percentile latency |          index-stats |   29.9786 |     ms |
|   All |  50.0th percentile service time |          index-stats |   1.53625 |     ms |
|   All |  90.0th percentile service time |          index-stats |   1.60196 |     ms |
|   All |  99.0th percentile service time |          index-stats |   1.92153 |     ms |
|   All | 100.0th percentile service time |          index-stats |   11.7068 |     ms |
|   All |                  Min Throughput |           node-stats |           |        |
|   All |               Median Throughput |           node-stats |           |        |
|   All |                  Max Throughput |           node-stats |           |        |
|   All |       50.0th percentile latency |           node-stats |   1.62292 |     ms |
|   All |       90.0th percentile latency |           node-stats |   1.80209 |     ms |
|   All |       99.0th percentile latency |           node-stats |   4.67785 |     ms |
|   All |      100.0th percentile latency |           node-stats |   13.2262 |     ms |
|   All |  50.0th percentile service time |           node-stats |   1.55853 |     ms |
|   All |  90.0th percentile service time |           node-stats |   1.74619 |     ms |
|   All |  99.0th percentile service time |           node-stats |   2.48444 |     ms |
|   All | 100.0th percentile service time |           node-stats |    13.168 |     ms |
|   All |                  Min Throughput |              default |           |  ops/s |
|   All |               Median Throughput |              default |           |  ops/s |
|   All |                  Max Throughput |              default |           |  ops/s |
|   All |                  Min Throughput |                 term |           |        |
|   All |               Median Throughput |                 term |           |        |
|   All |                  Max Throughput |                 term |           |        |
|   All |                  Min Throughput |               phrase |   200.104 |        |
|   All |               Median Throughput |               phrase |   200.123 |        |
|   All |                  Max Throughput |               phrase |   200.143 |        |
|   All |                  Min Throughput | country_agg_uncached |   6.16675 |        |
|   All |               Median Throughput | country_agg_uncached |   6.26778 |        |
|   All |                  Max Throughput | country_agg_uncached |   6.28171 |        |
|   All |                  Min Throughput |   country_agg_cached |    100.07 |        |
|   All |               Median Throughput |   country_agg_cached |   100.126 |        |
|   All |                  Max Throughput |   country_agg_cached |   100.182 |        |
|   All |                  Min Throughput |               scroll |   56.8402 |        |
|   All |               Median Throughput |               scroll |   56.8896 |        |
|   All |                  Max Throughput |               scroll |   57.0091 |        |
|   All |                  Min Throughput |           expression |   3.82189 |        |
|   All |               Median Throughput |           expression |   3.83776 |        |
|   All |                  Max Throughput |           expression |   3.86058 |        |
|   All |                  Min Throughput |      painless_static |   2.50521 |        |
|   All |               Median Throughput |      painless_static |   2.51079 |        |
|   All |                  Max Throughput |      painless_static |   2.51662 |        |
|   All |                  Min Throughput |     painless_dynamic |   2.23677 |        |
|   All |               Median Throughput |     painless_dynamic |   2.24671 |        |
|   All |                  Max Throughput |     painless_dynamic |   2.26263 |        |

Why are these empty?

|   All |                  Min Throughput |              default |           |  ops/s |
|   All |               Median Throughput |              default |           |  ops/s |
|   All |                  Max Throughput |              default |           |  ops/s |

**Comment by danielmitterdorfer** [comment]
@hexian55 Can you please provide some further information?

* Rally version
* How did you invoke Rally?

**Comment by danielmitterdorfer** [comment]
Closing as unrelated to tracks repo.
