### ISSUE TITLE
Migrate some `text` fields to `match_only_text`.

### ISSUE THREAD

**Issue by jpountz** [elastic/rally-tracks#170]
Elasticsearch 7.14 is introducing a more space-efficient variant of `text` called `match_only_text`. We should replace all `text` fields with `match_only_text` in our datasets where space efficiency is important to our users, such as:
 - the `request` field of `http_logs`,
 - the `request` and `referrer` fields of `eventdata`.

**Comment by jpountz** [comment]
For context, ECS is migrating its `text` fields to `match_only_text`. https://github.com/elastic/ecs/pull/1396

**Comment by ebadyano** [comment]
closed by https://github.com/elastic/rally-tracks/pull/181
