### ISSUE TITLE
TermQueryParamSource and SortedTermQueryParamSource Backwards

### ISSUE THREAD

**Issue by mattweber** [elastic/rally-tracks#18]
I was looking at your nested benchmarks and noticed that term query was slower than both nested and sorted term query.  This did not make sense to me so when I dug into the test I found you have mixed up TermQueryParamSource and SortedTermQueryParamSource.  TermQueryParamSource has a sort in the query and SortedTermQueryParamSource has no sort.  I just want to confirm that this was not intentional and is a bug in the benchmark.

https://github.com/elastic/rally-tracks/blob/master/nested/track.py#L27

**Comment by danielmitterdorfer** [comment]
That's mixed up indeed. Thanks for spotting it! I'll also correct our [nightly benchmark results](https://elasticsearch-benchmarks.elastic.co/nested/index.html#search_latency_queries).
