### ISSUE TITLE
Force-merge to one segment by default

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/rally-tracks#193]
Historically our tracks resort to the default behavior of the force-merge API and did not specify the desired number of segments. Recently we modified the force-merge behavior in several tracks (see https://github.com/elastic/rally-tracks/pull/185 and https://github.com/elastic/rally-tracks/pull/186) to improve stability of benchmark results. As this is desirable in general, we should change the default behavior in all tracks that peform any actions after indexing (see also #192) to force-merge to one segment unless specified otherwise (i.e. setting `max_num_segments` to `null`). Each track's README should include a clear indication of this behavior *and* an example how to achieve the behavior of force-merge.

**Comment by ebadyano** [comment]
After trying force merge with noaa, we decided that there was no noticeable improvement with stability, so doing force merge to one segment by default did not prove to be a suitable stability solution and needs to be done as needed by a benchmark. The change for noaa was reverted in https://github.com/elastic/rally-tracks/pull/204. closing this issue.
