### ISSUE TITLE
The error rate is 100%

### ISSUE THREAD

**Issue by Rawlinson-luo** [elastic/rally-tracks#32]
I use the geonames track,  and with a es cluster,the race result is:
|   All |                     error rate | index-append |        100 |      % |
|   All |                 Min Throughput |  force-merge |      16.61 |  ops/s |

the index-append failed, I am not sure the reson, maybe the es cluster maybe the esrally

**Comment by danielmitterdorfer** [comment]
Thanks for raising this but I think we should keep the discussion in https://discuss.elastic.co/t/the-error-rate-is-100/102117 as this problem is not related to the track (otherwise it would show that for everybody).
