### ISSUE TITLE
Move so_vector KNN operations to use _search endpoint

### ISSUE THREAD

**Issue by DJRickyB** [elastic/rally-tracks#331]
We should move the remaining KNN operations (those in the `so_vector` track) to use `search` operations. The only open question I have is if we should add a parameter source that supports randomness (like #330) or just convert the operations as they are.

CC @mayya-sharipova @jtibshirani

**Comment by jtibshirani** [comment]
I think adding a randomization option would also be helpful (as long as it's not too tricky?) That way, we could test random vectors alongside filters or text queries.
