### ISSUE TITLE
Add challenge with `search.default_search_timeout` cluster setting set

### ISSUE THREAD

**Issue by markharwood** [elastic/rally-tracks#35]
We are considering [setting a default timeout for elasticsearch clusters](https://github.com/elastic/elasticsearch/issues/27187 ) and want to understand the performance overheads of this. This issue is to create a clone of an existing challenge but with the timeout setting set in order to have an apples-to-apples basis for performing comparisons

**Comment by JalehD** [comment]
FYI support ( @joshuar @ppf2 ) has created this KB https://support.elastic.co/customers/s/article/Protecting-against-expensive-queries-in-Kibana to potentially recommend this setting `search.default_search_timeout` for customers who need to protect the cluster agains bad user queries so knowing the perf impact will be crucial before we recommend this en-mass

**Comment by markharwood** [comment]
@danielmitterdorfer - can you confirm approach below?

Presumably our objective here is to understand the _added cost_ of enabling a feature and we measure that cost by diffing using `rally compare` on 2 race outputs _from the same challenge_ - one pre-and-post setting change so comparisons are on results of identical operation sets. 

So the process for testing on `pmc` track would be:
  1) rally  --track=pmc --user-tag=intention:base_with_no_timeout
  2) edit  `rally-tracks/pmc/challenges/default.json` to add `search.default_search_timeout=60s` cluster setting
  3) rally  --track=pmc --user-tag=intention:contender_with_timeout
  4) rally compare --baseline=[basetimestamp] --contender=[contendertimestamp]
  
So this github issue wouldn't actually be committing a new challenge or adding an ongoing nightly scheduled test but sharing the results of a one-off comparison using the above steps for a selected challenge?

**Comment by danielmitterdorfer** [comment]
@markharwood these steps make sense to me. In step 2 you do not refer to a specific challenge but I guess you mean `append-no-conflicts` (the default one).

With the next release, Rally will allow to specify track parameters from the command line (see https://github.com/elastic/rally/issues/310) then you will not need to edit any files in step 2. I assume it will be a fair amount of work to make this work reliably though.

**Comment by danielmitterdorfer** [comment]
The latest master of Rally now allows to override track parameters from the command line. I've  [amended the PMC track](https://github.com/elastic/rally-tracks/blob/a3d5976db90cc1ded50c675c634a597d64c55a2a/pmc/challenges/default.json#L6) with a variable `search_timeout` so you can use `--track-params="search_timeout:'1m'"` to set the cluster setting `search.default_search_timeout` to 1 minute. This change is also backported for Elasticsearch 5.x and 2.x (1.x did not seem to support this parameter).

Now that there are no more changes necessary to any track, I think we can close this ticket?

**Comment by markharwood** [comment]
>Now that there are no more changes necessary to any track, I think we can close this ticket?

Agreed. I will close this and report the `rally compare` results on the original [let's set the default search timeout ](https://github.com/elastic/elasticsearch/issues/27187) issue
