### ISSUE TITLE
`raw-request` task in `nyc_taxis#esql` fails with `request [/_esql] contains unrecognized parameter: [request_timeout]"`

### ISSUE THREAD

**Issue by dliappis** [elastic/rally-tracks#393]
I think this is related to the `elasticsearch-py` upgrade to 8.x in Rally (I haven't tested with an older version yet), but when running the `nyc_taxis/esql` track we are getting:

```
Running multi_terms-keyword_esql_shard_partitioning                            [  0% done][ERROR] Cannot race. Error in load generator [0]
        Cannot run task [multi_terms-keyword_esql_shard_partitioning]: Request returned an error. Error type: api, Description: <_io.BytesIO object at 0x7f836ba36e80> ({"error":{"root_cause":[{"type":"illegal_argument_exception","reason":
"request [/_esql] contains unrecognized parameter: [request_timeout]"}],"type":"illegal_argument_exception","reason":"request [/_esql] contains unrecognized parameter: [request_timeout]"},"status":400})                                    
```

Without digging deeper, I think this is because the particular task is a `raw-request` and we are specifying `request-timeout`: https://github.com/elastic/rally-tracks/blob/20b81839236d2184748f94f8a58071ac5f3f2194/nyc_taxis/operations/default.json#L1175) which, according to https://github.com/elastic/rally/issues/1673, it should be, instead, in `client.options()`?

If yes, I see at least two ways to work around this:

1. Switch from `raw-request` to a custom runner and manipulate the timeout there
2. Add logic in the `raw-request` runner of Rally to do that itself

**Comment by dliappis** [comment]
cc @csoulios

**Comment by b-deam** [comment]
https://github.com/elastic/rally/pull/1705 closed this.
