### ISSUE TITLE
403 Access denied, when esrally tries to download workloads.

### ISSUE THREAD

**Issue by vsegdacocacola** [elastic/rally-tracks#45]
Hi,

I am receiving 403 Access denied, when esrally tries to download workloads.

http://benchmarks.elasticsearch.org.s3.amazonaws.com/corpora/http_logs/documents-181998.json.bz2

Do I need specific access to s3 bucket?

**Comment by jiaqingw** [comment]
same here

**Comment by danielmitterdorfer** [comment]
Thanks for the pointer. We are looking into it.

**Comment by danielmitterdorfer** [comment]
we have restored access to the bucket:

```
 curl -I http://benchmarks.elasticsearch.org.s3.amazonaws.com/corpora/http_logs/documents-181998.json.bz2
HTTP/1.1 200 OK
```
