### ISSUE TITLE
Branching for backward compatibilty: 8.7 and later

### ISSUE THREAD

**Issue by inqueue** [elastic/rally-tracks#474]
Changes introduced in https://github.com/elastic/rally-tracks/commit/249332baa3560ee342432c5041bd71015e086d7f have broken backward compatibility for pre-8.x versions of Elasticsearch, specifically, 8.7 and later. What is needed:

* Create a branch aligning with the ES version where the change is compatible; i.e., 8.11.
* To fix 8.7, remove any incompatible track operations from the 8.7 branch.

**Comment by gbanasiak** [comment]
cc @craigtaverner

**Comment by gbanasiak** [comment]
@craigtaverner agreed on complete ESQL challenge removal in 8.7 branch so I've raised https://github.com/elastic/rally-tracks/pull/483.
