### ISSUE TITLE
Deprecatied frequent-items, change to frequent-items_sets

### ISSUE THREAD

**Issue by ebadyano** [elastic/rally-tracks#557]
When running `frequent-items` challenge in https://github.com/elastic/rally-tracks/tree/master/so on ES 8 there is a deprecation warning:
```
  "event.code": "deprecated_field_frequent_items",
  "message": "Deprecated field [frequent_items] used, expected [frequent_item_sets] instead",
```

**Comment by davidkyle** [comment]
Thanks for the ping @ebadyano 

The frequent_items aggregation was renamed to frequent_item_sets in 8.7 almost a year ago. Will this track ever run against a pre 8.7 cluster? If not we will make the change to frequent_item_sets


> I can't seem to find when that will be removed

There's a code comment suggesting 9.0

**Comment by ebadyano** [comment]
@davidkyle The way rally deals with different elasticsearch vesions/changes in rally tracks is that it uses different branch of rally-tracks, so once you submit a pr, I can backport the change to all the branches up 8.7.
