### ISSUE TITLE
Which license do your queries have?

### ISSUE THREAD

**Issue by lquenti** [elastic/rally-tracks#567]
Hey,
we currently use the nyc_taxis track for some internal evaluation that may or may not result in a paper, of course citing the directory.

Under which license are the queries you designed? Is it the same license as rally (Apache-2)?

**Comment by gareth-ellis** [comment]
Hello, the license can vary per track - so it's best to check the README for the individual track - for nyc taxis for example it is https://github.com/elastic/rally-tracks/tree/master/nyc_taxis#license

**Comment by lquenti** [comment]
Yes! I saw that one, thanks! But I think this only applies to the corpus itself, not the scripts or other track definitions such as operations, right?
