### ISSUE TITLE
Add a track for geo_shape

### ISSUE THREAD

**Issue by jpountz** [elastic/rally-tracks#60]
We should add a track for `geo_shape`.

@iverase @nknize @imotov Who wants to own this?

**Comment by imotov** [comment]
I would be interested in doing this, but I might need some help with finding good datasets.

**Comment by nknize** [comment]
http://people.apache.org/~nknize/planetOSMShapes.subset.wkt  is the 60M Planet OSM Shape corpus we use for lucene. Would be good to use this (or a further subset) for rally. **WARNING** its ~40GB file.
