### ISSUE TITLE
percolator_with_content_ignore_me param 

### ISSUE THREAD

**Issue by Jiangzhuoyan** [elastic/rally-tracks#63]
![image](https://user-images.githubusercontent.com/11457465/52026942-a05d8c80-2544-11e9-874e-aaefd4294244.png)
 I test percolator_no_score_with_content_ignore_me is 200 times better than percolator_with_content_ignore_me in  Median Throughput, is this param is wrong?

**Comment by danielmitterdorfer** [comment]
This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/c/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/c/elasticsearch/rally) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
