### ISSUE TITLE
eventdata track seems to have incorrect index reference

### ISSUE THREAD

**Issue by GlenRSmith** [elastic/rally-tracks#75]
In the eventdata track challenges, there is a `check-cluster-health` task defined that has `"index": "logs-*"` but AFAICT there are no such indices involved in the track. Should that be `"index": "eventdata"`?

**Comment by danielmitterdorfer** [comment]
Good catch and thanks for reporting! I've pushed a fix in https://github.com/elastic/rally-tracks/commit/28ab4a9a68cd183eba0da1bab85a09d0c03f09f0 and the next time you invoke Rally it should pull the latest changes automatically and behave as you specified.
