### ISSUE TITLE
Big difference between the two measurements,Does esrally cheating?

### ISSUE THREAD

**Issue by Liujinan001** [elastic/rally-tracks#95]
**Problems:**
I run twice esrally testings(each testing only perform “index-append”), but the result are very different.

**Step:**
1.create the index geonames manually
2.First test: 
esrally race --pipeline=benchmark-only --target-hosts=28.28.0.4:9200 --track=geonames
The result:
|Min Throughput 		| index-append |    144447 | docs/s |
|Median Throughput 	| index-append |    209693 | docs/s |
|Max Throughput 		| index-append |    225118 | docs/s |

3.delete the index geonames manually
4.create the index geonames manually
5.Second test:
esrally race --pipeline=benchmark-only --target-hosts=28.28.0.4:9200 --track=geonames
The result:
|Min Throughput 		| index-append |    228746 | docs/s |
|Median Throughput 	| index-append |    256881 | docs/s |
|Max Throughput 		| index-append |    263886 | docs/s |

The throughput of the two measurements is very different,about 50000 docs/s.I repeated the testing many times, and this result will appear.

Why?

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Rally.

This appears to be a user question, and we'd like to direct these kinds of things to the [Rally forum](https://discuss.elastic.co/c/elasticsearch/rally). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch/rally) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

As a quick pointer, I recommend you checkout our blog post [Seven Tips for Better Elasticsearch Benchmarks](https://www.elastic.co/blog/seven-tips-for-better-elasticsearch-benchmarks), especially the section around warmup.
