### ISSUE TITLE
Add a Twitter track

### ISSUE THREAD

**Issue by AmineBenatmane** [elastic/rally-tracks#96]
Twitter Analytics Platforms are one of the most popular ELK uses cases. I think we should consider adding it.

**Comment by danielmitterdorfer** [comment]
Thanks for your interest in Rally! Can you please elaborate what you mean by "Twitter Analytics Platform"? Here are some additional questions that also need an answer before we can think about this:

* What is the exact use-case / workload? What is covered there, that's not covered by the other Rally tracks?
* Where to get the data from? Are they available under a permissive license (like creative commons, Apache, etc)?
* How large is the data set? Is it suitable for benchmarking (several GB, ideally several tens of GB large)?
* What kind of data set is this? (i.e. how does the mapping look like)?

**Comment by danielmitterdorfer** [comment]
Closing due to lack of feedback.
